### ISSUE TITLE
Building Impossible

### ISSUE THREAD

**Issue by DaGeRe** [t2-project/microservices#1]
The project cannot be built, first, since mvnw isn't executable (just do chmod +x mvnw and commit), and second, since an error appears during compilation:

> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project e2etest: Could not resolve dependencies for project de.unistuttgart.t2:e2etest:jar:1.3.1-SNAPSHOT
> [ERROR] dependency: de.unistuttgart.t2:order:original:1.3.1-SNAPSHOT (compile)
> [ERROR] 	Could not find artifact de.unistuttgart.t2:order:original:1.3.1-SNAPSHOT
> [ERROR] dependency: de.unistuttgart.t2:inventory:original:1.3.1-SNAPSHOT (compile)
> [ERROR] 	Could not find artifact de.unistuttgart.t2:inventory:original:1.3.1-SNAPSHOT
> [ERROR] dependency: de.unistuttgart.t2:payment:original:1.3.1-SNAPSHOT (compile)
> [ERROR] 	Could not find artifact de.unistuttgart.t2:payment:original:1.3.1-SNAPSHOT

Is there an easy fix for this?

**Comment by DaGeRe** [comment]
Sorry, my bad - with `install` instead of `package`, it works (although its surprising that just packaging doesn't work). But the executable flag still needs to be set here.

**Comment by davidkopp** [comment]
Thank you for creating all the issues!

I have now fixed the issue that mvnw wasn't executable by using `git update-index --chmod=+x mvnw` in all repositories. 

The Maven command `install` is required instead of `package` because of how the build for e2e-tests works.
`package` works if you exclude e2e-tests from the build:

```sh
./mvnw clean package -pl \!e2e-tests -DskipTests=true 
```
